trying to isolate cause of [main] ERROR org.apache.streams.pig.StreamsProcessorExec - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.streams.data.util.RFC3339Utils